### ISSUE TITLE
Error launching new module based on python decorator

### ISSUE THREAD

**Issue by kryptoss** [voiser/zoe-startup-kit#11]
When Zoe launches the module, the log shows:
Traceback (most recent call last):
  File "./memory.py", line 3, in <module>
    import zoe
  File "/home/almacen/devel/zoe/zoe-startup-kit/lib/python/zoe/__init__.py", line 28, in <module>
    from zoe.zs import * 
  File "/home/almacen/devel/zoe/zoe-startup-kit/lib/python/zoe/zs.py", line 29, in <module>
    import configparser
ImportError: No module named configparser

**Comment by rmed** [comment]
Are you using python 3 (`#!/usr/bin/env python3`)? The name of the configparser module in python 2 was `ConfigParser`, which might explain that error, as tree decorator lib is for 3.x .
